### ISSUE TITLE
relations and properties

### ISSUE THREAD

**Issue by thomasPerles** [thomaslecointre/KMP-2.0#21]
On branch develop : ![capture d ecran 1](https://user-images.githubusercontent.com/17743676/35483874-9f56be2a-0447-11e8-9ba7-f7fd52b85f4f.png)

**Comment by thomaslecointre** [comment]
C'est inspect relations et pas insert :)

Le 28 janv. 2018 4:25 PM, "Thomas Perles" <notifications@github.com> a
écrit :
